[package]
name = "rust-tesira-text-protocol"
description = "Implementation of Tesira Text Protocol to communicate with biamp Tesira devices"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = "8.0"
thiserror = "2.0"
